// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FinCa")>]
[<assembly: AssemblyProductAttribute("FinCa")>]
[<assembly: AssemblyDescriptionAttribute("Personal Financial App")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FinCa"
    let [<Literal>] AssemblyProduct = "FinCa"
    let [<Literal>] AssemblyDescription = "Personal Financial App"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
